export enum AdjustmenType {
      Assessment = 'Average Assessment consumption',
      CLFUnits = 'CLF Unrts',
      CaptiveUnits = 'Captive Units',
      DLFUnits = 'DLF Units',
      IndustrialUnits = 'Industrial Units',
      ManualReading = 'Manual Reading Entry',
      ManualUnits = 'Manual Units',
      MiningUnits = 'Mining Units',
      OpenAccessUnits = 'Open Access Units',
      PartAssessment = 'Part Assessment',
      REBiomassEnergy = 'RE Unit for Biomass Energy',
      REHydelEnergy = 'RE Unit for Hydel Energy',
      REOtherEnergy = 'RE Unit for Other Energy',
      RESolarEnergy = 'RE Unit for Solar Energy',
      REWindEnergy = 'RE Unit for Wind Energy',
      RMTUnits = 'RMT Units',
      SolarGenerabon = 'Solar Generabon Units',
      SubMeterConsumpsion = 'Sub-Meter Consumpsion',
      TMMUnits = 'TMM Units',
      WindFarmUnits = 'Wind Farm Units',
}
